# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  workflow_dispatch:
  repository_dispatch:
    types: [static]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to pages
        run: |
          mkdir ./pages
          cp ./vpm.json ./pages/vpm.json
          cp ./README.md ./pages/README.md

      - name: Checkout VCCPageBuilder
        uses: actions/checkout@v4
        with:
          repository: Sonic853/VCCPageBuilder
          path: vccbuilder

      - name: Get dll file
        run: |
          mkdir ./vccbuilder/vpm-core-lib
          wget -O ./vccbuilder/vpm-core-lib/vpm-core-lib.dll https://github.com/vrchat-community/package-list-action/raw/main/vpm-core-lib/vpm-core-lib.dll

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build VCCPageBuilder
        run: dotnet publish ./vccbuilder/VCCPageBuilder/VCCPageBuilder.csproj -c Release -o ./vccbuilder/output /p:PublishSingleFile=true /p:RuntimeIdentifier=linux-x64 /p:SelfContained=false

      - name: Run VCCPageBuilder
        run: |
          ./vccbuilder/output/VCCPageBuilder --vpm ./pages/vpm.json --source ./source.json --web WebTemplate --out pages

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
